FROM $VESPA_BASE_IMAGE

# Don't autostart anything when building image
RUN yinst set root.autostart=off

RUN yinst install -branch test yruby-2.3.1_1 vespa_test-$(yinst ls vespa | grep -Eo "[0-9]\.[0-9]+\.[0-9]+") vespa_systemtest_deps

# Start node_server through bash to avoid zombie processes, see
# https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
ENTRYPOINT ["/bin/bash", "-c", "set -e && /systemtests/bin/node_server.rb"]
