# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://vespa-engine.github.io/vespa/"

git_url = "https://github.com/vespa-engine/vespa/tree/master/"

def custom_doc_links(name): return None
