#!/usr/bin/env bash
# Copyright 2019 Oath Inc. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

eval $(vespa-security-env)

$VESPA_HOME/libexec/vespa/GetClusterState.pl "$@"