name: "dummy_transformer"
platform: "onnxruntime_onnx"
max_batch_size: 1
instance_group {
  count: 1
  kind: KIND_CPU
}
parameters {
  key: "enable_mem_area"
  value {
    string_value: "0"
  }
}
parameters {
  key: "enable_mem_pattern"
  value {
    string_value: "0"
  }
}
parameters {
  key: "inter_op_thread_count"
  value {
    string_value: "5"
  }
}
parameters {
  key: "intra_op_thread_count"
  value {
    string_value: "5"
  }
}
