name: "dummy_transformer_1a8ed485e2c11b1b"
platform: "onnxruntime_onnx"
max_batch_size: 1
instance_group {
  count: 12
  kind: KIND_CPU
}
parameters {
  key: "enable_mem_area"
  value {
    string_value: "0"
  }
}
parameters {
  key: "enable_mem_pattern"
  value {
    string_value: "0"
  }
}
parameters {
  key: "inter_op_thread_count"
  value {
    string_value: "2"
  }
}
parameters {
  key: "intra_op_thread_count"
  value {
    string_value: "1"
  }
}
