// Copyright 2016 Yahoo Inc. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

#pragma once

#include <vespa/metrics/metric.h>
#include <vespa/vespalib/util/xmlserializable.h>

namespace metrics {

class XmlWriter : public MetricVisitor {
    uint32_t _period;
    vespalib::xml::XmlOutputStream& _xos;
    int _verbosity;

public:
    XmlWriter(vespalib::xml::XmlOutputStream& xos,
              uint32_t period, int verbosity);

    virtual bool visitSnapshot(const MetricSnapshot&);
    virtual void doneVisitingSnapshot(const MetricSnapshot&);
    virtual bool visitMetricSet(const MetricSet& set, bool);
    virtual void doneVisitingMetricSet(const MetricSet&);
    virtual bool visitCountMetric(const AbstractCountMetric&,
                                  bool autoGenerated);
    virtual bool visitValueMetric(const AbstractValueMetric&,
                                  bool autoGenerated);

private:
    void printCommonXmlParts(const Metric& metric) const;
};

}

