// Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
package com.yahoo.vespa.hosted.controller.routing.rotation;

import com.yahoo.text.Text;

import java.util.Objects;

/**
 * Represents a global routing rotation.
 *
 * @author mpolden
 */
public record Rotation(RotationId id, String name) {

    public Rotation {
        Objects.requireNonNull(id);
        Objects.requireNonNull(name);
    }

    /** The ID of the allocated rotation. This value is generated by global routing system */
    public RotationId id() {
        return id;
    }

    /** The global rotation FQDN */
    public String name() {
        return name;
    }

    @Override
    public String toString() {
        return Text.format("rotation %s -> %s", id().asString(), name());
    }

}
