// Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
package com.yahoo.searchdefinition;

import ai.vespa.rankingexpression.importer.configmodelview.ImportedMlModels;
import com.yahoo.collections.Pair;
import com.yahoo.search.query.profile.QueryProfile;
import com.yahoo.search.query.profile.QueryProfileRegistry;
import com.yahoo.search.query.profile.types.FieldDescription;
import com.yahoo.search.query.profile.types.QueryProfileType;
import com.yahoo.searchdefinition.derived.AttributeFields;
import com.yahoo.searchdefinition.derived.RawRankProfile;
import com.yahoo.searchdefinition.parser.ParseException;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.assertEquals;

/**
 * @author lesters
 */
public class RankingExpressionFeatureArgumentsTestCase extends SchemaTestCase {

    @Test
    public void testFeatureWithExpressionArguments() throws ParseException {
        RankProfileRegistry rankProfileRegistry = new RankProfileRegistry();
        SearchBuilder builder = new SearchBuilder(rankProfileRegistry);
        builder.importString(
                "search test {\n" +
                        "    document test { \n" +
                        "        field t1 type tensor<float>(x{}) { \n" +
                        "            indexing: attribute | summary \n" +
                        "        }\n" +
                        "        field t2 type tensor<float>(x{}) { \n" +
                        "            indexing: attribute | summary \n" +
                        "        }\n" +
                        "    }\n" +
                        "    rank-profile test {\n" +
                        "        function my_func(t) {\n" +
                        "            expression: sum(t, x) \n" +
                        "        }\n" +
                        "        function test() {\n" +
                        "            expression: my_func( attribute(t1) * attribute(t2) ) \n" +
                        "        }\n" +
                        "        function test2() {\n" +
                        "            expression: test3( attribute(t1), attribute(t2) ) \n" +
                        "        }\n" +
                        "        function inline test3(a, b) {\n" +
                        "            expression: my_func( a * b ) \n" +
                        "        }\n" +
                        "        first-phase {\n" +
                        "            expression: 42 \n" +
                        "        }\n" +
                        "    }\n" +
                        "\n" +
                        "}\n");
        builder.build();
        Search s = builder.getSearch();
        RankProfile test = rankProfileRegistry.get(s, "test").compile(new QueryProfileRegistry(), new ImportedMlModels());
        List<Pair<String, String>> testRankProperties = new RawRankProfile(test,
                new QueryProfileRegistry(),
                new ImportedMlModels(),
                new AttributeFields(s)).configProperties();

        for(Pair<String,String> prop : testRankProperties) {
            System.out.println(prop.getFirst() + ": " + prop.getSecond());
        }

        assertEquals("(rankingExpression(my_func@45673ba956ae9b77).rankingScript,reduce(autogenerated_ranking_feature@43bc412603c00a4a, sum, x))",
                testRankProperties.get(2).toString());
        assertEquals("(rankingExpression(test).rankingScript,rankingExpression(my_func@45673ba956ae9b77))",
                testRankProperties.get(3).toString());
        assertEquals("(rankingExpression(test3@640470df47a83000.c156faa8f98c0b0c).rankingScript,rankingExpression(my_func@45673ba956ae9b77))",
                testRankProperties.get(4).toString());
        assertEquals("(rankingExpression(test2).rankingScript,rankingExpression(test3@640470df47a83000.c156faa8f98c0b0c))",
                testRankProperties.get(5).toString());
    }

}
