// Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
// NOTE: This file was generated by the 'create-fef-includes.sh' script


/**
 * @file fef.h
 *
 * This is a convenience header that will include everything you need
 * to use this library.
 **/

#pragma once

#include <vespa/searchlib/common/feature.h>

#include "blueprint.h"
#include "blueprintfactory.h"
#include "blueprintresolver.h"
#include "featureexecutor.h"
#include "featurenamebuilder.h"
#include "featurenameparser.h"
#include "featureoverrider.h"
#include "fieldinfo.h"
#include "fieldpositionsiterator.h"
#include "fieldtype.h"
#include "filetablefactory.h"
#include "functiontablefactory.h"
#include "handle.h"
#include "iblueprintregistry.h"
#include "idumpfeaturevisitor.h"
#include "iindexenvironment.h"
#include "indexproperties.h"
#include "iqueryenvironment.h"
#include "itablefactory.h"
#include "itablemanager.h"
#include "itermdata.h"
#include "itermfielddata.h"
#include "matchdata.h"
#include "matchdatalayout.h"
#include "parameter.h"
#include "parameterdescriptions.h"
#include "parametervalidator.h"
#include "phrasesplitter.h"
#include "properties.h"
#include "queryproperties.h"
#include "rank_program.h"
#include "ranksetup.h"
#include "simpletermdata.h"
#include "simpletermfielddata.h"
#include "symmetrictable.h"
#include "table.h"
#include "tablemanager.h"
#include "termfieldmatchdata.h"
#include "termfieldmatchdataarray.h"
#include "termfieldmatchdataposition.h"
#include "termmatchdatamerger.h"
#include "utils.h"
#include "verify_feature.h"

