// Copyright 2016 Yahoo Inc. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
package com.yahoo.docproc;

/**
 * Exception generated by known bad input in a docproc. Will cause only message to be logged,
 * not stacktrace.
 *
 * @author <a href="mailto:mathiasm@yahoo-inc.com">Mathias M\u00F8lster Lidal</a>
 */
public class HandledProcessingException extends RuntimeException {

    public HandledProcessingException(String message) {
        super(message);
    }
}
