// Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
package com.yahoo.vespa.hosted.controller.api.rotation;

import com.yahoo.vespa.hosted.controller.api.identifiers.RotationId;

import java.util.Objects;

/**
 * Represents a global routing rotation.
 *
 * @author Oyvind Gronnesby
 */
public class Rotation {

    /** The ID of the allocated rotation. This value is generated by global routing system. */
    public final RotationId rotationId;

    /** The global name which the allocated rotation points to */
    public final String rotationName;

    public Rotation(RotationId rotationId, String rotationName) {
        this.rotationId = Objects.requireNonNull(rotationId);
        this.rotationName = Objects.requireNonNull(rotationName);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Rotation)) return false;
        final Rotation rotation = (Rotation) o;
        return rotationId.equals(rotation.rotationId) && rotationName.equals(rotation.rotationName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(rotationId, rotationName);
    }

}
