# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
  <style type="text/css">

    body {
        margin: 3em;
    }

    body, p, div, div, span, dl, li, pre {
        font-size: 16px;
        line-height: 22px;
    }

    header h1 {
        font-size: 54px;
        line-height: 1;
    }

    section {
        padding-top: 60px;
    }

    ol.linenums {
        padding-left: 20px;
    }

    pre, pre * {
        font-size: 14px !important;
    }

    li.L0, li.L1, li.L2, li.L3, li.L4, li.L5, li.L6, li.L7, li.L8, li.L9
    {
        color: #bbb;
        list-style-type: decimal;
    }

    h2 {
        padding-top: 20px;
        padding-bottom: 10px;
    }
    
    pre.output {
        border: 1px solid #888;
    }

    code {
        color: #444;
        border: 0;
        background-color: transparent;
    }

  </style>
