// Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
package com.yahoo.jdisc.bundle.k;

/**
 * @author Simon Thoresen Hult
 */
@SuppressWarnings({ "UnusedDeclaration", "deprecation", "removal" })
public class CertificateK {

    private final com.google.common.annotations.Beta beta = null;
    private final com.google.common.base.Ascii ascii = null;
    private final com.google.common.cache.CacheStats stats = null;
    private final com.google.common.collect.BoundType boundType = null;
    private final com.google.common.eventbus.DeadEvent deadEvent = null;
    private final com.google.common.hash.Funnels funnels = null;
    private final com.google.common.io.ByteArrayDataInput dataInput = null;
    private final com.google.common.math.BigIntegerMath math = null;
    private final com.google.common.net.HostAndPort hostAndPort = null;
    private final com.google.common.primitives.Booleans booleans = null;
    private final com.google.common.reflect.Reflection reflection = null;
    private final com.google.common.util.concurrent.AbstractIdleService idleService = null;
    private final com.google.inject.AbstractModule module = null;
    private final com.google.inject.binder.AnnotatedConstantBindingBuilder builder = null;
    private final com.google.inject.matcher.Matchers matchers = null;
    private final com.google.inject.multibindings.MapBinder<String, String> mapBinder = null;
    private final com.google.inject.name.Named named = null;
    private final com.google.inject.spi.Elements elements = null;
    private final com.google.inject.util.Modules modules = null;
    private final com.yahoo.config.BooleanNode node = null;
    private final com.yahoo.jdisc.AbstractResource resource = null;
    private final com.yahoo.jdisc.application.AbstractApplication application = null;
    private final com.yahoo.jdisc.handler.AbstractRequestHandler handler = null;
    private final com.yahoo.jdisc.service.AbstractClientProvider client = null;
    private final com.yahoo.yolean.concurrent.ThreadRobustList<?> robustList = null;
    private final com.yahoo.yolean.trace.TraceNode traceNode = null;
    private final com.sun.security.auth.LdapPrincipal principal = null;
    private final com.sun.security.auth.module.JndiLoginModule jndiLoginModule = null;
    private final java.security.cert.Certificate certificate = null;
    private final javax.accessibility.Accessible accessible = null;
    private final javax.annotation.processing.FilerException filerException = null;
    private final javax.crypto.BadPaddingException badPaddingException = null;
    private final javax.crypto.interfaces.DHKey dhKey = null;
    private final javax.crypto.spec.DHParameterSpec dhParameterSpec = null;
    private final javax.imageio.IIOException iioException = null;
    private final javax.imageio.event.IIOReadProgressListener iioReadProgressListener = null;
    private final javax.imageio.metadata.IIOInvalidTreeException iioInvalidTreeException = null;
    private final javax.imageio.plugins.bmp.BMPImageWriteParam bmpImageWriteParam = null;
    private final javax.imageio.plugins.jpeg.JPEGHuffmanTable jpegHuffmanTable = null;
    private final javax.imageio.spi.IIORegistry iioRegistry = null;
    private final javax.imageio.stream.FileCacheImageInputStream fileCacheImageInputStream = null;
    private final javax.lang.model.SourceVersion sourceVersion = null;
    private final javax.lang.model.element.AnnotationMirror annotationMirror = null;
    private final javax.lang.model.type.ArrayType arrayType = null;
    private final javax.lang.model.util.AbstractAnnotationValueVisitor6<?,?> abstractAnnotationValueVisitor6 = null;
    private final javax.management.Attribute attribute = null;
    private final javax.management.loading.ClassLoaderRepository classLoaderRepository = null;
    private final javax.management.modelmbean.DescriptorSupport descriptorSupport = null;
    private final javax.management.monitor.CounterMonitor counterMonitor = null;
    private final javax.management.openmbean.CompositeData compositeData = null;
    private final javax.management.relation.InvalidRelationIdException invalidRelationIdException = null;
    private final javax.management.remote.JMXAddressable jmxAddressable = null;
    private final javax.management.remote.rmi.RMIConnection rmiConnection = null;
    private final javax.management.timer.Timer timer = null;
    private final javax.naming.AuthenticationException authenticationException = null;
    private final javax.naming.directory.AttributeInUseException attributeInUseException = null;
    private final javax.naming.event.EventContext eventContext = null;
    private final javax.naming.ldap.BasicControl basicControl = null;
    private final javax.naming.spi.DirectoryManager directoryManager = null;
    private final javax.net.ServerSocketFactory serverSocketFactory = null;
    private final javax.net.ssl.CertPathTrustManagerParameters certPathTrustManagerParameters = null;
    private final javax.print.AttributeException attributeException = null;
    private final javax.print.attribute.AttributeSet attributeSet = null;
    private final javax.print.attribute.standard.Chromaticity chromaticity = null;
    private final javax.print.event.PrintEvent printEvent = null;
    private final javax.rmi.ssl.SslRMIClientSocketFactory sslRMIClientSocketFactory = null;
    private final javax.script.AbstractScriptEngine abstractScriptEngine = null;
    private final javax.security.auth.AuthPermission authPermission = null;
    private final javax.security.auth.callback.ChoiceCallback choiceCallback = null;
    private final javax.security.auth.kerberos.DelegationPermission delegationPermission = null;
    private final javax.security.auth.login.AccountException accountException = null;
    private final javax.security.auth.spi.LoginModule loginModule = null;
    private final javax.security.auth.x500.X500Principal x500Principal = null;
    private final javax.security.cert.Certificate deprecatedCertificate = null;
    private final javax.security.sasl.AuthorizeCallback authorizeCallback = null;
    private final javax.sound.midi.ControllerEventListener controllerEventListener = null;
    private final javax.sound.midi.spi.MidiDeviceProvider midiDeviceProvider = null;
    private final javax.sound.sampled.AudioFileFormat audioFileFormat = null;
    private final javax.sound.sampled.spi.AudioFileReader audioFileReader = null;
    private final javax.sql.CommonDataSource commonDataSource = null;
    private final javax.sql.rowset.BaseRowSet baseRowSet = null;
    private final javax.sql.rowset.serial.SerialArray serialArray = null;
    private final javax.sql.rowset.spi.SyncFactory syncFactory = null;
    private final javax.swing.AbstractAction abstractAction = null;
    private final javax.swing.border.AbstractBorder abstractBorder = null;
    private final javax.swing.colorchooser.AbstractColorChooserPanel abstractColorChooserPanel = null;
    private final javax.swing.event.AncestorEvent ancestorEvent = null;
    private final javax.swing.filechooser.FileFilter fileFilter = null;
    private final javax.swing.plaf.ActionMapUIResource actionMapUIResource = null;
    private final javax.swing.plaf.basic.BasicArrowButton basicArrowButton = null;
    private final javax.swing.plaf.metal.DefaultMetalTheme defaultMetalTheme = null;
    private final javax.swing.plaf.multi.MultiButtonUI multiButtonUI = null;
    private final javax.swing.plaf.synth.ColorType colorType = null;
    private final javax.swing.table.AbstractTableModel abstractTableModel = null;
    private final javax.swing.text.AbstractDocument abstractDocument = null;
    private final javax.swing.text.html.BlockView blockView = null;
    private final javax.swing.text.html.parser.AttributeList attributeList = null;
    private final javax.swing.text.rtf.RTFEditorKit rtfEditorKit = null;
    private final javax.swing.tree.AbstractLayoutCache abstractLayoutCache = null;
    private final javax.swing.undo.AbstractUndoableEdit abstractUndoableEdit = null;
    private final javax.tools.FileObject fileObject = null;
    private final javax.transaction.xa.XAException xaException = null;
    private final javax.xml.XMLConstants xmlConstants = null;
    private final javax.xml.crypto.AlgorithmMethod algorithmMethod = null;
    private final javax.xml.crypto.dom.DOMCryptoContext domCryptoContext = null;
    private final javax.xml.crypto.dsig.CanonicalizationMethod canonicalizationMethod = null;
    private final javax.xml.crypto.dsig.dom.DOMSignContext domSignContext = null;
    private final javax.xml.crypto.dsig.keyinfo.KeyInfo keyInfo = null;
    private final javax.xml.crypto.dsig.spec.C14NMethodParameterSpec c14NMethodParameterSpec = null;
    private final javax.xml.datatype.DatatypeConfigurationException datatypeConfigurationException = null;
    private final javax.xml.namespace.NamespaceContext namespaceContext = null;
    private final javax.xml.parsers.DocumentBuilder documentBuilder = null;
    private final javax.xml.stream.EventFilter eventFilter = null;
    private final javax.xml.stream.events.Characters characters = null;
    private final javax.xml.stream.util.EventReaderDelegate eventReaderDelegate = null;
    private final javax.xml.transform.ErrorListener errorListener = null;
    private final javax.xml.transform.dom.DOMLocator domLocator = null;
    private final javax.xml.transform.sax.SAXResult saxResult = null;
    private final javax.xml.transform.stax.StAXResult stAXResult = null;
    private final javax.xml.transform.stream.StreamResult streamResult = null;
    private final javax.xml.validation.Schema schema = null;
    private final javax.xml.xpath.XPath xPath = null;
    private final org.aopalliance.intercept.Joinpoint jointpoint = null;
    private final org.aopalliance.aop.Advice advice = null;
    private final org.apache.commons.logging.LogFactory logFactory = null;
    private final org.apache.commons.logging.impl.SimpleLog simpleLog = null;
    private final org.apache.log4j.Appender appender = null;
    private final org.apache.log4j.helpers.LogLog logLog = null;
    private final org.apache.log4j.spi.ErrorHandler errorHandler = null;
    private final org.apache.log4j.xml.DOMConfigurator configurator = null;
    private final org.ietf.jgss.ChannelBinding channelBinding = null;
    private final org.osgi.framework.AdminPermission permission = null;
    private final org.osgi.framework.hooks.service.FindHook hook = null;
    private final org.osgi.framework.launch.Framework framework = null;
    private final org.osgi.service.packageadmin.ExportedPackage pkg = null;
    private final org.osgi.service.startlevel.StartLevel level = null;
    private final org.osgi.service.url.URLConstants constants = null;
    private final org.osgi.util.tracker.BundleTracker<?> tracker = null;
    private final org.slf4j.ILoggerFactory loggerFactory = null;
    private final org.slf4j.spi.LocationAwareLogger locationAwareLogger = null;
    private final org.slf4j.helpers.BasicMarker basicMarker = null;
    private final org.slf4j.impl.StaticLoggerBinder staticLoggerBinder = null;
    private final org.w3c.dom.Attr attr = null;
    private final org.w3c.dom.bootstrap.DOMImplementationRegistry domImplementationRegistry = null;
    private final org.w3c.dom.css.Counter counter = null;
    private final org.w3c.dom.events.EventException eventException = null;
    private final org.w3c.dom.html.HTMLAnchorElement htmlAnchorElement = null;
    private final org.w3c.dom.ls.DOMImplementationLS domImplementationLS = null;
    private final org.w3c.dom.ranges.DocumentRange documentRange = null;
    private final org.w3c.dom.stylesheets.DocumentStyle documentStyle = null;
    private final org.w3c.dom.traversal.DocumentTraversal documentTraversal = null;
    private final org.w3c.dom.views.DocumentView documentView = null;
    private final org.xml.sax.ContentHandler contentHandler = null;
    private final org.xml.sax.ext.Attributes2Impl attributes2 = null;
    private final org.xml.sax.helpers.AttributesImpl attributes = null;


    // Packages made invisible from Java 9

    // Added as dep in jdisc_core: com.sun.activation:javax.activation (OSGi bundle)
    private final com.sun.activation.viewers.ImageViewer imageViewer = null;
    private final com.sun.activation.registries.MimeTypeFile mimeTypeFile = null;
    private final javax.activation.CommandInfo commandInfo = null;

    // Added as dep in jdisc_core: javax.xml.bind:jaxb-api (OSGi bundle)
    private final javax.xml.bind.DataBindingException dataBindingException = null;
    private final javax.xml.bind.annotation.DomHandler<?,?> domHandler = null;
    private final javax.xml.bind.annotation.adapters.CollapsedStringAdapter collapsedStringAdapter = null;
    private final javax.xml.bind.attachment.AttachmentMarshaller attachmentMarshaller = null;
    private final javax.xml.bind.helpers.AbstractMarshallerImpl abstractMarshaller = null;
    private final javax.xml.bind.util.JAXBResult jaxbResult = null;

}
