#!/bin/bash
# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

set -eo pipefail

PIPELINE="$BUILDKITE_PLUGIN_FACTORY_REPORTER_PIPELINE_ID"
FIRST_STEP="$BUILDKITE_PLUGIN_FACTORY_REPORTER_FIRST_STEP"

if [[ $SKIP_BUILDKITE_PLUGINS == "true" ]]; then
    echo "SKIP_BUILDKITE_PLUGINS is set. Skipping factory reporter"
    exit 0
fi
if [[ $BUILDKITE_PULL_REQUEST != "false" ]]; then
    echo "This is a pull request, skipping factory reporter"
    exit 0
fi
if [[ -z $PIPELINE ]]; then
    echo "No pipeline ID found, skipping factory reporter"
    exit 0
fi

if [[ -z $FIRST_STEP ]] || [[ $FIRST_STEP != "true" ]]; then
    echo "Not first step, skipping build creation"
    exit 0
fi

JSON=$($BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/factory-command.sh create-build $PIPELINE)

echo "Output from creating build : $JSON"

VESPA_FACTORY_BUILD_ID=$(jq -re '.buildId' <<< "$JSON")
export VESPA_FACTORY_BUILD_ID

echo "Created factory build $VESPA_FACTORY_BUILD_ID for pipeline $PIPELINE"

$BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/factory-command.sh update-build-status $PIPELINE running "Building"

echo "Set factory build $VESPA_FACTORY_BUILD_ID status to running"
