// Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
package com.yahoo.docproc.impl;

/**
 * Exception generated by known bad input in a docproc. Will cause only message to be logged,
 * not stacktrace.
 *
 * @author Mathias Mølster Lidal
 */
public class HandledProcessingException extends RuntimeException {

    public HandledProcessingException(String message) {
        super(message);
    }

}
