#!/usr/bin/perl -w
# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

use strict;

my @pids = `ps auxww | grep "./testrunner" | grep -v grep`;
foreach (@pids) {
    s/^\S+\s+(\d+)\s+.*$/$1/;
    chomp;
}

foreach my $pid (@pids) {
    my $cmd = "pstack $pid";
    system($cmd) == 0 or die "Failed to run '$cmd'";
}
