#!/bin/sh
# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

ps auxww | grep "./testrunner" | grep -v grep | while read username pid restofline; do
	if pstack $pid; then :; else
		echo "Failed to run 'pstack $pid'"
		exit 1
	fi
done
