// Copyright 2020 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
package com.yahoo.container.jdisc;

import java.util.List;

/**
 * A handler can implement this to be included in the "links" section generated by the BindingsOverviewHandler.
 *
 * @author ogronnesby
 */
public interface NavigableRequestHandler {
    List<HandlerEntryPoint> entryPoints();
}
