// Copyright 2016 Yahoo Inc. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
/* Last autogenerated file */

#pragma once

#define FASTOS_64BIT_LONG         1
#define FASTOS_HAVE_INT64_T       1
#define FASTOS_HAVE_UINT64_T      1
#define FASTOS_HAVE_INT32_T       1
#define FASTOS_HAVE_UINT32_T      1
#define FASTOS_HAVE_INT16_T       1
#define FASTOS_HAVE_UINT16_T      1
#define FASTOS_HAVE_INT8_T        1
#define FASTOS_HAVE_UINT8_T       1
#define FASTOS_HAVE_INT64_T       1
#define FASTOS_HAVE_SOCKLEN_T     1
