package ai.vespa.schemals.lsp.yqlplus.semantictokens;

import java.util.HashMap;
import java.util.Map;

import org.eclipse.lsp4j.SemanticTokenTypes;

import com.yahoo.collections.Pair;
import com.yahoo.search.cluster.Hasher;

import ai.vespa.schemals.parser.grouping.ast.ACCURACY;
import ai.vespa.schemals.parser.grouping.ast.ACOS;
import ai.vespa.schemals.parser.grouping.ast.ACOSH;
import ai.vespa.schemals.parser.grouping.ast.ADD;
import ai.vespa.schemals.parser.grouping.ast.ALIAS;
import ai.vespa.schemals.parser.grouping.ast.ALL;
import ai.vespa.schemals.parser.grouping.ast.AND;
import ai.vespa.schemals.parser.grouping.ast.AS;
import ai.vespa.schemals.parser.grouping.ast.ASIN;
import ai.vespa.schemals.parser.grouping.ast.ASINH;
import ai.vespa.schemals.parser.grouping.ast.AT;
import ai.vespa.schemals.parser.grouping.ast.ATAN;
import ai.vespa.schemals.parser.grouping.ast.ATANH;
import ai.vespa.schemals.parser.grouping.ast.ATTRIBUTE;
import ai.vespa.schemals.parser.grouping.ast.AVG;
import ai.vespa.schemals.parser.grouping.ast.BUCKET;
import ai.vespa.schemals.parser.grouping.ast.CAT;
import ai.vespa.schemals.parser.grouping.ast.CBRT;
import ai.vespa.schemals.parser.grouping.ast.COS;
import ai.vespa.schemals.parser.grouping.ast.COSH;
import ai.vespa.schemals.parser.grouping.ast.COUNT;
import ai.vespa.schemals.parser.grouping.ast.DEBUGWAIT;
import ai.vespa.schemals.parser.grouping.ast.DOCIDNSSPECIFIC;
import ai.vespa.schemals.parser.grouping.ast.EACH;
import ai.vespa.schemals.parser.grouping.ast.EQ;
import ai.vespa.schemals.parser.grouping.ast.EXP;
import ai.vespa.schemals.parser.grouping.ast.FALSE;
import ai.vespa.schemals.parser.grouping.ast.FILTER;
import ai.vespa.schemals.parser.grouping.ast.FIXEDWIDTH;
import ai.vespa.schemals.parser.grouping.ast.FLOOR;
import ai.vespa.schemals.parser.grouping.ast.GROUP;
import ai.vespa.schemals.parser.grouping.ast.GT;
import ai.vespa.schemals.parser.grouping.ast.HINT;
import ai.vespa.schemals.parser.grouping.ast.HYPOT;
import ai.vespa.schemals.parser.grouping.ast.INF;
import ai.vespa.schemals.parser.grouping.ast.INFIX_ADD;
import ai.vespa.schemals.parser.grouping.ast.INFIX_DIV;
import ai.vespa.schemals.parser.grouping.ast.INFIX_MOD;
import ai.vespa.schemals.parser.grouping.ast.INFIX_MUL;
import ai.vespa.schemals.parser.grouping.ast.INFIX_SUB;
import ai.vespa.schemals.parser.grouping.ast.INTERPOLATEDLOOKUP;
import ai.vespa.schemals.parser.grouping.ast.LOG;
import ai.vespa.schemals.parser.grouping.ast.LOG10;
import ai.vespa.schemals.parser.grouping.ast.LOG1P;
import ai.vespa.schemals.parser.grouping.ast.LT;
import ai.vespa.schemals.parser.grouping.ast.MATH;
import ai.vespa.schemals.parser.grouping.ast.MAX;
import ai.vespa.schemals.parser.grouping.ast.MD5;
import ai.vespa.schemals.parser.grouping.ast.MIN;
import ai.vespa.schemals.parser.grouping.ast.MOD;
import ai.vespa.schemals.parser.grouping.ast.MUL;
import ai.vespa.schemals.parser.grouping.ast.NEG;
import ai.vespa.schemals.parser.grouping.ast.NEGINF;
import ai.vespa.schemals.parser.grouping.ast.NORMALIZESUBJECT;
import ai.vespa.schemals.parser.grouping.ast.NOT;
import ai.vespa.schemals.parser.grouping.ast.NOW;
import ai.vespa.schemals.parser.grouping.ast.OR;
import ai.vespa.schemals.parser.grouping.ast.ORDER;
import ai.vespa.schemals.parser.grouping.ast.OUTPUT;
import ai.vespa.schemals.parser.grouping.ast.POW;
import ai.vespa.schemals.parser.grouping.ast.PRECISION;
import ai.vespa.schemals.parser.grouping.ast.PREDEFINED;
import ai.vespa.schemals.parser.grouping.ast.QUANTILES;
import ai.vespa.schemals.parser.grouping.ast.RANGE;
import ai.vespa.schemals.parser.grouping.ast.REGEX;
import ai.vespa.schemals.parser.grouping.ast.RELEVANCE;
import ai.vespa.schemals.parser.grouping.ast.REVERSE;
import ai.vespa.schemals.parser.grouping.ast.SIN;
import ai.vespa.schemals.parser.grouping.ast.SINH;
import ai.vespa.schemals.parser.grouping.ast.SIZE;
import ai.vespa.schemals.parser.grouping.ast.SORT;
import ai.vespa.schemals.parser.grouping.ast.SQRT;
import ai.vespa.schemals.parser.grouping.ast.STDDEV;
import ai.vespa.schemals.parser.grouping.ast.STRCAT;
import ai.vespa.schemals.parser.grouping.ast.STRLEN;
import ai.vespa.schemals.parser.grouping.ast.STRING;
import ai.vespa.schemals.parser.grouping.ast.SUB;
import ai.vespa.schemals.parser.grouping.ast.SUM;
import ai.vespa.schemals.parser.grouping.ast.SUMMARY;
import ai.vespa.schemals.parser.grouping.ast.TAN;
import ai.vespa.schemals.parser.grouping.ast.TANH;
import ai.vespa.schemals.parser.grouping.ast.TIME;
import ai.vespa.schemals.parser.grouping.ast.TIME_DATE;
import ai.vespa.schemals.parser.grouping.ast.TIME_DAYOFMONTH;
import ai.vespa.schemals.parser.grouping.ast.TIME_DAYOFWEEK;
import ai.vespa.schemals.parser.grouping.ast.TIME_DAYOFYEAR;
import ai.vespa.schemals.parser.grouping.ast.TIME_HOUROFDAY;
import ai.vespa.schemals.parser.grouping.ast.TIME_MINUTEOFHOUR;
import ai.vespa.schemals.parser.grouping.ast.TIME_MONTHOFYEAR;
import ai.vespa.schemals.parser.grouping.ast.TIME_SECONDOFMINUTE;
import ai.vespa.schemals.parser.grouping.ast.TIME_YEAR;
import ai.vespa.schemals.parser.grouping.ast.TODOUBLE;
import ai.vespa.schemals.parser.grouping.ast.TOLONG;
import ai.vespa.schemals.parser.grouping.ast.TORAW;
import ai.vespa.schemals.parser.grouping.ast.TOSTRING;
import ai.vespa.schemals.parser.grouping.ast.TRUE;
import ai.vespa.schemals.parser.grouping.ast.UCA;
import ai.vespa.schemals.parser.grouping.ast.WHERE;
import ai.vespa.schemals.parser.grouping.ast.X;
import ai.vespa.schemals.parser.grouping.ast.XOR;
import ai.vespa.schemals.parser.grouping.ast.XORBIT;
import ai.vespa.schemals.parser.grouping.ast.Y;
import ai.vespa.schemals.parser.grouping.ast.ZCURVE;
import ai.vespa.schemals.parser.grouping.ast.andFunction;
import ai.vespa.schemals.parser.grouping.ast.andPredicate;
import ai.vespa.schemals.parser.grouping.ast.identifierStr;
import ai.vespa.schemals.parser.grouping.ast.notPredicate;
import ai.vespa.schemals.parser.grouping.ast.number;
import ai.vespa.schemals.parser.grouping.ast.orFunction;
import ai.vespa.schemals.parser.grouping.ast.orPredicate;
import ai.vespa.schemals.parser.grouping.ast.stringElm;

class VespaGroupingSemanticToken {

    private static final String timeFunctionType = SemanticTokenTypes.Method;
    private static final String mathFunctionType = SemanticTokenTypes.Method;
    private static final String operationBodyFunction = SemanticTokenTypes.Function;
    private static final String simpleExpressions = SemanticTokenTypes.Macro;
    private static final String logicalFilter = SemanticTokenTypes.Operator;

    static final Map<Class<?>, String> tokensMap = new HashMap<Class<?>, String>() {{
        put(EQ.class, SemanticTokenTypes.Operator);
        put(FALSE.class, SemanticTokenTypes.Type);
        put(GT.class, SemanticTokenTypes.Operator);
        put(INF.class, SemanticTokenTypes.Number);
        put(INFIX_ADD.class, SemanticTokenTypes.Operator);
        put(INFIX_DIV.class, SemanticTokenTypes.Operator);
        put(INFIX_MOD.class, SemanticTokenTypes.Operator);
        put(INFIX_MUL.class, SemanticTokenTypes.Operator);
        put(INFIX_SUB.class, SemanticTokenTypes.Operator);
        put(LT.class, SemanticTokenTypes.Operator);
        put(NEGINF.class, SemanticTokenTypes.Number);
        put(STRING.class, SemanticTokenTypes.String);
        put(TRUE.class, SemanticTokenTypes.Type);
        put(identifierStr.class, SemanticTokenTypes.Variable);
        put(number.class, SemanticTokenTypes.Number);
        put(stringElm.class, SemanticTokenTypes.String);

        put(TIME.class, SemanticTokenTypes.Class);
        put(TIME_DATE.class, timeFunctionType);
        put(TIME_DAYOFMONTH.class, timeFunctionType);
        put(TIME_DAYOFWEEK.class, timeFunctionType);
        put(TIME_DAYOFYEAR.class, timeFunctionType);
        put(TIME_HOUROFDAY.class, timeFunctionType);
        put(TIME_MINUTEOFHOUR.class, timeFunctionType);
        put(TIME_MONTHOFYEAR.class, timeFunctionType);
        put(TIME_SECONDOFMINUTE.class, timeFunctionType);
        put(TIME_YEAR.class, timeFunctionType);

        put(ACOS.class, mathFunctionType);
        put(ACOSH.class, mathFunctionType);
        put(ASIN.class, mathFunctionType);
        put(ASINH.class, mathFunctionType);
        put(ATAN.class, mathFunctionType);
        put(ATANH.class, mathFunctionType);
        put(CBRT.class, mathFunctionType);
        put(COS.class, mathFunctionType);
        put(COSH.class, mathFunctionType);
        put(EXP.class, mathFunctionType);
        put(FLOOR.class, mathFunctionType);
        put(HYPOT.class, mathFunctionType);
        put(LOG.class, mathFunctionType);
        put(LOG10.class, mathFunctionType);
        put(LOG1P.class, mathFunctionType);
        put(MATH.class, SemanticTokenTypes.Class);
        put(POW.class, mathFunctionType);
        put(SIN.class, mathFunctionType);
        put(SINH.class, mathFunctionType);
        put(SQRT.class, mathFunctionType);
        put(TAN.class, mathFunctionType);
        put(TANH.class, mathFunctionType);

        put(ALL.class, SemanticTokenTypes.Keyword);
        put(EACH.class, SemanticTokenTypes.Keyword);


        put(ACCURACY.class, operationBodyFunction);
        put(ALIAS.class, operationBodyFunction);
        put(FILTER.class, operationBodyFunction);
        put(GROUP.class, operationBodyFunction);
        put(HINT.class, operationBodyFunction);
        put(MAX.class, operationBodyFunction);
        put(ORDER.class, operationBodyFunction);
        put(OUTPUT.class, operationBodyFunction);
        put(PRECISION.class, operationBodyFunction);
        put(WHERE.class, operationBodyFunction);

        put(AS.class, SemanticTokenTypes.Keyword);
        put(AT.class, SemanticTokenTypes.Keyword);

        put(ADD.class, simpleExpressions);
        put(ALIAS.class, simpleExpressions); // TODO: Verify that this is a function
        put(ATTRIBUTE.class, simpleExpressions);
        put(AVG.class, simpleExpressions);
        put(BUCKET.class, simpleExpressions);
        put(CAT.class, simpleExpressions);
        put(COUNT.class, simpleExpressions);
        put(DEBUGWAIT.class, simpleExpressions); // TODO: Maybe add a warning on this function
        put(DOCIDNSSPECIFIC.class, simpleExpressions);
        put(FIXEDWIDTH.class, simpleExpressions);
        put(INTERPOLATEDLOOKUP.class, simpleExpressions);
        put(MAX.class, simpleExpressions);
        put(MD5.class, simpleExpressions);
        put(MIN.class, simpleExpressions);
        put(MOD.class, simpleExpressions);
        put(MUL.class, simpleExpressions);
        put(NEG.class, simpleExpressions);
        put(NORMALIZESUBJECT.class, simpleExpressions);
        put(NOW.class, simpleExpressions);
        put(PREDEFINED.class, simpleExpressions);
        put(QUANTILES.class, simpleExpressions);
        put(RANGE.class, simpleExpressions);
        put(REGEX.class, simpleExpressions);
        put(RELEVANCE.class, simpleExpressions);
        put(REVERSE.class, simpleExpressions);
        put(SIZE.class, simpleExpressions);
        put(SORT.class, simpleExpressions);
        put(STDDEV.class, simpleExpressions);
        put(STRCAT.class, simpleExpressions);
        put(STRLEN.class, simpleExpressions);
        put(SUB.class, simpleExpressions);
        put(SUM.class, simpleExpressions);
        put(SUMMARY.class, simpleExpressions);
        put(TODOUBLE.class, simpleExpressions);
        put(TOLONG.class, simpleExpressions);
        put(TORAW.class, simpleExpressions);
        put(TOSTRING.class, simpleExpressions);
        put(UCA.class, simpleExpressions);
        put(XOR.class, simpleExpressions);
        put(XORBIT.class, simpleExpressions);

        put(X.class, SemanticTokenTypes.Method);
        put(Y.class, SemanticTokenTypes.Method);
        put(ZCURVE.class, SemanticTokenTypes.Class);
    }};

    static final Map<Pair<Class<?>, Class<?>>, String> tokensMapWithParent = new HashMap<>() {{
        put(new Pair<>(AND.class, andPredicate.class), logicalFilter);
        put(new Pair<>(OR.class, orPredicate.class), logicalFilter);
        put(new Pair<>(NOT.class, notPredicate.class), logicalFilter);

        put(new Pair<>(AND.class, andFunction.class), simpleExpressions);
        put(new Pair<>(OR.class, orFunction.class), simpleExpressions);
    }};
}
