name: Sync CODEOWNERS

on:
  pull_request:
    branches: [ "master" ]
    paths: [ "**/OWNERS", ".github/CODEOWNERS" ]

permissions:
  contents: write

jobs:
  codeowners:
    uses: vespa-engine/gh-actions/.github/workflows/sync-codeowners.yml@main
