name: Link check

on:
  workflow_dispatch:

  pull_request:
    branches:
      - master

  schedule:
    - cron: '0 2 * * 1-5'

jobs:
  link-check:
    runs-on: ubuntu-latest

    container:
      image: ruby:3.3
      volumes:
        - ${{ github.workspace }}:/workspace

    defaults:
      run:
        working-directory: /workspace

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          gem update --system 3.3.3
          gem install bundler
          export LANG=C.UTF-8
          bundle install

      - name: Add front matter for processing
        run: |
          find . -not -path './_site/*' -name \*.md | \
            while read f; do (echo -e "---\nrender_with_liquid: false\n---\n"; cat ${f})>${f}.new; mv ${f}.new ${f}; done

      - name: Build site
        run: |
          bundle exec jekyll build

      - name: Check links
        run: |
          bundle exec htmlproofer \
          --assume-extension --check-html --no-check-external-hash --no-enforce-http \
          --typhoeus '{"connecttimeout": 10, "timeout": 30, "followlocation": false}' \
          --hydra '{"max_concurrency": 1}' \
          --ignore-urls '/slack.vespa.ai/,/localhost:8080/,/127.0.0.1:3000/,/favicon.svg/,/main.jsx/' \
          --ignore-files '/fnet/index.html/,/client/js/app/node_modules/' \
          --swap-urls '(.*).md:\1.html' \
          _site
