name: Mirror Copr RPMs to archive

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/mirror-copr-rpms-to-archive.yml
      - .github/scripts/publish-unpublished-rpms-to-archive.sh
      - .github/scripts/upload-rpm-to-cloudsmith.sh
    branches:
      - master

  schedule:
   - cron: '0 6 * * *'

jobs:
  mirror-copr-rpms-to-archive:
    runs-on: ubuntu-latest

    container:
        image: almalinux:8
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          CLOUDSMITH_API_TOKEN: ${{ secrets.CLOUDSMITH_API_TOKEN }}
        volumes:
          - ${{ github.workspace }}:/workspace

    defaults:
      run:
        working-directory: /workspace

    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          dnf install -y dnf-plugins-core jq

      - name: Publish to ${{ matrix.arch }} mirror
        run: |
          .github/scripts/publish-unpublished-rpms-to-archive.sh ${{ matrix.arch }}
