name: Verify open source RPM installable

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/verify-opensource-rpm-installable.yml
    branches:
      - master

  schedule:
   - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  verify-opensource-rpm-installable:
    runs-on: ubuntu-latest

    container:
      image: almalinux:8@sha256:8b469a3a78515e8a18ea8fc727e6a3679e1d0c5ba6f58d5b30be3d0d9b86cffe

    steps:
      - name: Install Vespa
        run: |
          dnf list llvm-libs --showduplicates
          dnf install -y dnf-plugins-core
          dnf -y config-manager --add-repo https://raw.githubusercontent.com/vespa-engine/vespa/master/dist/vespa-engine.repo
          dnf config-manager --enable powertools
          dnf install -y epel-release
          dnf install -y vespa
