name: Verify open source RPM installable

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/verify-opensource-rpm-installable.yml
    branches:
      - master

  schedule:
   - cron: '0 0 * * *'

jobs:
  verify-opensource-rpm-installable:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - almalinux-version: 8
            crb-repo: powertools
          - almalinux-version: 9
            crb-repo: crb

    container:
      image: almalinux:${{ matrix.almalinux-version }}

    steps:
      - name: Install Vespa
        run: |
          dnf list llvm-libs --showduplicates
          dnf install -y dnf-plugins-core
          dnf -y config-manager --add-repo https://raw.githubusercontent.com/vespa-engine/vespa/master/dist/vespa-engine.repo
          dnf config-manager --enable ${{ matrix.crb-repo }}
          dnf install -y epel-release
          dnf install -y vespa
