name: Verify OSS RPMs

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/verify-opensource-rpm-installable.yml
    branches:
      - master

  schedule:
   - cron: '0 0 * * *'

jobs:
  install:
    name: Almalinux ${{ matrix.almalinux-major }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        almalinux-major: [8, 9]

    container:
      image: almalinux:${{ matrix.almalinux-major }}

    steps:
      - name: Install Vespa
        run: |
          dnf list llvm-libs --showduplicates
          dnf install -y dnf-plugins-core
          dnf -y config-manager --add-repo https://raw.githubusercontent.com/vespa-engine/vespa/master/dist/vespa-engine.repo
          dnf config-manager --enable powertools
          dnf install -y epel-release
          dnf install -y vespa
